---
{{- if eq .Values.global.secretStore.backend "aws-secrets-manager" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-accesskey-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.ocpExternalSecrets.aws.region }}
      auth:
        # Reference the Kubernetes Secret containing the credentials
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
            namespace: kube-system
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
            namespace: kube-system
{{- end }}
